# Generated by Django 5.0.1 on 2024-01-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
        migrations.RenameField(
            model_name='universityclasses',
            old_name='instructor_name',
            new_name='instructor',
        ),
    ]
